### ISSUE TITLE
`custom_virtualenv_dir` doesn't work

### ISSUE THREAD

**Issue by ark0f** [syphar/restore-virtualenv#490]
> Warning: Unexpected input(s) 'custom_virtualenv_dir', valid inputs are ['custom_cache_key_element', 'requirement_files']

**Comment by syphar** [comment]
can you check which version/tag you are using? Can you post the piece where you use the parameter here?

**Comment by ark0f** [comment]
![image](https://user-images.githubusercontent.com/21154701/176937916-77d31b0d-c70e-4e66-b765-c876daf023a7.png)

**Comment by syphar** [comment]
Ah, I see what happened. 

When releasing v1.2 I didn't update the v1 tag as I should have. 

When you retry you should be fine.

**Comment by ark0f** [comment]
Now it works. Thanks
