### ISSUE TITLE
[Question] can be used with matrix strategy?

### ISSUE THREAD

**Issue by codebydant** [syphar/restore-virtualenv#692]
Hi @syphar,

Thanks for this wonderful tool. I was wondering if there is support for running this action with matrix strategy since it seems it failed because the action tries to write to the same cache location.

**Comment by syphar** [comment]
hi @dtcMLOps , 

I intentionally wanted to enable sharing the virtualenv between jobs, which is why the default cache key is built like it is. 

You can use a different `custom_cache_key_element`, using an element from the matrix to make this work.
